# yaml-language-server: $schema=../vendor/symfony/dependency-injection/Loader/schema/services.schema.json

parameters:

services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\:
        resource: '../src/'

    App\Service\StripeService:
        arguments:
            $secretKey: '%env(STRIPE_SECRET_KEY)%'
            $publicKey: '%env(STRIPE_PUBLIC_KEY)%'
            $appUrl:    '%env(APP_URL)%'

    App\Service\MailerSendService:
        arguments:
            $apiKey:    '%env(MAILERSEND_API_KEY)%'
            $fromEmail: '%env(MAILER_FROM_EMAIL)%'
            $fromName:  '%env(MAILER_FROM_NAME)%'

    App\Service\PdfTicketService:
        arguments:
            $twig: '@twig'

    App\Service\ExchangeRateService:
        arguments:
            $apiKey:       '%env(EXCHANGE_RATE_API_KEY)%'
            $baseCurrency: '%env(EXCHANGE_RATE_BASE_CURRENCY)%'

    App\Service\AiOfferService:
        arguments:
            $apiKey: '%env(GROQ_API_KEY)%'
    
    App\Repository\OfferActivityRepository:
        arguments:
            $connection: '@doctrine.dbal.default_connection'